#!/usr/bin/env node
'use strict';
var Vogogo = require('../lib/vogogo');
var config = require('../config');

if (!process.argv[9] || process.argv[10]) {
  console.log('usage: ./addBankAccount <customer> <name> <institution> <transit> <routing> <number> <currency> <financial_type>');
  process.exit();
}

var params = {
  name: process.argv[3],
  institution: process.argv[4],
  transit: process.argv[5],
  routing: process.argv[6],
  number: process.argv[7],
  currency: process.argv[8],
  financial_type: process.argv[9],
};

var options = config.authParams;
options.apiPrefix = config.environments[config.defaultEnvironment].apiPrefix;
options.customerAccessToken = process.argv[2];

var vogogo = new Vogogo(options);

vogogo.addBankAccount(params, function(err) {
  if (err) {
    console.log(err);
  } else {
    console.log('Success');
  }
});
