#!/usr/bin/env node
'use strict';
var Vogogo = require('../lib/vogogo');
var config = require('../config');

if (process.argv[3]) {
  console.log('usage: ./createCustomer');
  process.exit();
}

var params = {};

var options = config.authParams;
options.apiPrefix = config.environments[config.defaultEnvironment].apiPrefix;

var vogogo = new Vogogo(options);

vogogo.createCustomer(params, function(err, result) {
  if (err) {
    console.log(err);
  } else if (!result) {
    console.log('no results from Vogogo');
  } else {
    console.log(result);
  }
});
