#!/usr/bin/env node
'use strict';
var Vogogo = require('../lib/vogogo');
var config = require('../config');

if (process.argv[4] || !process.argv[3]) {
  console.log('usage: ./getAccounts <customer> <currency>');
  process.exit();
}

var params = {};

params.currency = process.argv[3];

var options = config.authParams;
options.apiPrefix = config.environments[config.defaultEnvironment].apiPrefix;
options.customerAccessToken = process.argv[2];

var vogogo = new Vogogo(options);

vogogo.getAccounts(params, function(err, accounts) {
  if (err) {
    console.log(err);
  } else if (!accounts) {
    console.log('no results from Vogogo');
  } else {
    console.log(accounts);
  }
});
