#!/usr/bin/env node
'use strict';
var Vogogo = require('../lib/vogogo');
var config = require('../config');

if (!process.argv[3] || process.argv[4]) {
  console.log('usage: ./getTransaction <customer> <id>');
  process.exit();
}

var params = {
  id: process.argv[3]
};

var options = config.authParams;
options.apiPrefix = config.environments[config.defaultEnvironment].apiPrefix;
options.customerAccessToken = process.argv[2];

var vogogo = new Vogogo(options);

vogogo.getTransaction(params, function(err, transaction) {
  if (err) {
    console.log(err);
  } else if (!transaction) {
    console.log('no results from Vogogo');
  } else {
    console.log(transaction);
  }
});
