#!/usr/bin/env node
'use strict';
var Vogogo = require('../lib/vogogo');
var config = require('../config');

if (!process.argv[2] || process.argv[3]) {
  console.log('usage: ./pay <customer>');
  process.exit();
}

var params = {
  customerId: process.argv[2],
};

var options = config.authParams;
options.apiPrefix = config.environments[config.defaultEnvironment].apiPrefix;
options.ipAddress = config.ipAddress;
options.deviceId = config.deviceId;

var vogogo = new Vogogo(options);

vogogo.listBankAccounts(params, function(err, body) {
  if (err) {
    console.log(err);
  } else {
    console.log(body);
  }
});
