#!/usr/bin/env node
'use strict';
var Vogogo = require('../lib/vogogo');
var config = require('../config');

if (process.argv[4] || !process.argv[2]) {
  console.log('usage: ./listTransactions <customer> <currency> (optional)');
  process.exit();
}

var params = {
  customerAccessToken: process.argv[2],
};

var currency = process.argv[3];
if (currency) {
  params.currency = currency;
}

var options = config.authParams;
options.apiPrefix = config.environments[config.defaultEnvironment].apiPrefix;

var vogogo = new Vogogo(options);

vogogo.listTransactions(params, function(err, transactions) {
  if (err) {
    console.log(err);
  } else if (!transactions) {
    console.log('no results from Vogogo');
  } else {
    console.log(JSON.stringify(transactions, null, 3));
  }
});
