#!/usr/bin/env node
'use strict';
var Vogogo = require('../lib/vogogo');
var config = require('../config');

if (process.argv[3]) {
  console.log('usage: ./listTransactions <currency> (optional)');
  process.exit();
}

var params = {};

var currency = process.argv[2];
if (currency) {
  params.currency = currency;
}

var options = config.authParams;
options.apiPrefix = config.environments[config.defaultEnvironment];

var vogogo = new Vogogo(options);

vogogo.listTransactions(params, function(err, transactions) {
  if (err) {
    console.log(err);
  } else if (!transactions) {
    console.log('no results from Vogogo');
  } else {
    console.log(transactions);
  }
});
