#!/usr/bin/env node
'use strict';
var Vogogo = require('../lib/vogogo');
var config = require('../config');

if (!process.argv[6] || process.argv[7]) {
  console.log('usage: ./pay <customer> <payment id> <account_id> <amount> <currency>');
  process.exit();
}

var params = {
  id: process.argv[3],
  account_id: process.argv[4],
  amount: process.argv[5],
  currency: process.argv[6],
  ip: '127.0.0.1'
};

var options = config.authParams;
options.apiPrefix = config.environments[config.defaultEnvironment].apiPrefix;
options.customerAccessToken = process.argv[2];

var vogogo = new Vogogo(options);

vogogo.pay(params, function(err) {
  if (err) {
    console.log(err);
  } else {
    console.log('Success');
  }
});
