#!/usr/bin/env node
'use strict';
var Vogogo = require('../lib/vogogo');
var config = require('../config');

if (!process.argv[6] || process.argv[7]) {
  console.log('usage: ./pay <customer> <transaction id> <account_id> <amount> <currency>');
  process.exit();
}

var params = {
  customerId: process.argv[2],
  merchant_transaction_id: process.argv[3],
  account_id: process.argv[4],
  amount: process.argv[5],
  currency: process.argv[6],
  type: 'pay',
  device_id: 'qwertyuiop'
};

var options = config.authParams;
options.apiPrefix = config.environments[config.defaultEnvironment].apiPrefix;
options.ipAddress = config.ipAddress;
options.deviceId = config.deviceId;

var vogogo = new Vogogo(options);

vogogo.pay(params, function(err) {
  if (err) {
    console.log(err);
  } else {
    console.log('Success');
  }
});
