#!/usr/bin/env node
'use strict';
var Vogogo = require('../lib/vogogo');
var config = require('../config');

if (process.argv[4] || !process.argv[2]) {
  console.log('usage: ./removeBankAccount <customer> <bankAccountId>');
  process.exit();
}

var params = {
  customerId: process.argv[2],
  bankAccountId: process.argv[3]
};

var options = config.authParams;
options.apiPrefix = config.environments[config.defaultEnvironment].apiPrefix;
options.ipAddress = config.ipAddress;
options.deviceId = config.deviceId;

var vogogo = new Vogogo(options);

vogogo.removeBankAccount(params, function(err, result) {
  if (err) {
    console.log(err);
  } else if (!result) {
    console.log('no result from Vogogo');
  } else {
    console.log(JSON.stringify(result, null, 3));
  }
});
